### ISSUE TITLE
cmdtime dont work very well with args of commands

### ISSUE THREAD

**Issue by JaegerFox** [mookid/broken_utils#3]
```
cmdtime chdman createcd -i foo.cue -o bar.chd
Error: Expected option, not parameter
```
or am i doing something wrong

I tried to search all over the internet and I can't find anything

**Comment by mookid** [comment]
hey, sorry I missed your question. from a quick googling it seems that this message comes from the chdman command?  https://forums.libretro.com/t/extracting-chd-files/15717/6

Does the same command without cmdtime work at all?

**Comment by JaegerFox** [comment]
yes, using the same command without cmdtime works

**Comment by mookid** [comment]
so one difference is that cmdtime will not pick up .bat files in your path. what is the output of `where chdman`? if the bat file comes first, it might explain the difference.

in that case the workaround is to use `cmdtime chdman.bat createcd -i foo.cue -o bar.chd` instead.

If not, I am out if ideas.

**Comment by JaegerFox** [comment]
I think the problem is that cmdtime does not support arguments without hyphen, for example `cmdtime chdman.exe -i foo.cue `would support it, but not `cmdtime chdman.exe createcd -i foo.cue`

**Comment by mookid** [comment]
I am not sure what you mean; command with or without hyphens are supposed to be supported.

To debug, you can try to print the lpCommandLine passed to CreateProcessW.

**Comment by JaegerFox** [comment]
I really don't know how to do that, it was easier to try it yourself, it is not necessary to do it with an iso of a game, you can also use an iso of a linux distro
